Add styleUrls to component snippet
johnpapa/vscode-angular-snippets pull request #23
Opened 2016-09-25 17:33 UTC by third774

Figured this should be included in the snippet since templateUrl is already included.

2017-01-20 18:22 UTC, johnpapa commented
thanks.

i go back and forth on this ... still thinking it over.

2017-01-23 08:34 UTC, SamVerschueren requested changes

2017-01-23 08:34 UTC, SamVerschueren commented on snippets/typescript.json
>        "\ttemplateUrl: '${feature}.component.html'",
You forgot a comma after this line.

2017-03-02 13:57 UTC, joachimprinzbach commented
In my opinion, only the basic set should be included. 
- I am working iteratively - when I create a new component I don't know yet whether I will need a stylesheet later on
- I don't like removing code from a generated boilerplate, it's a better appraoch to add the stylesUrl when you need it

2017-03-02 13:59 UTC, johnpapa commented
I tend to agree that less is better.

2017-03-02 13:59 UTC, johnpapa commented
thanks, for submitting, but often we dont need styles for a component, and i dont like adding code folks have to delete. thanks tho!

2017-03-02 13:59 UTC, closed without merging